spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  sql:
    init:
      mode: always
      defer-datasource-initialization: true
  data:
    rest:
      default-page-size: 10
      return-body-on-create: true
      return-body-on-update: true
logging:
  level:
    org.springframework.data.rest: INFO
